spring.application.name=inkflow-api
server.port=8080

# Conexão com o Banco de Dados (Ajuste para suas credenciais)
spring.datasource.url=jdbc:postgresql://localhost:5432/inkflow_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true