spring.application.name=inkflow-api
server.port=8080

# Conexão com o Banco de Dados (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/inkflow_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=seu_usuario_mysql
spring.datasource.password=sua_senha_mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect